## Importing required libraries: 

In [4]:
import cv2 as cv ##For image processing.
import PIL ## Python Imaging Library for handling images.                        
import numpy as np ## For numerical operations.
import pandas as pd ##For data manipulation and analysis.
import os ##For connecting the file paths from system
import matplotlib.pyplot as plt ##plotting

## Defining the paths for training and test datasets:

In [6]:
train_path = r"C:\Users\YASH CHAUDHARY\Desktop\project1\\Yash_chaudhary\\Neural networks\\train\\train"
test_path = r"C:\Users\YASH CHAUDHARY\Desktop\project1\\Yash_chaudhary\\Neural networks\\test\\test"

## Looping through the test and train data folders and printing the names of folders existing:

In [7]:
for folder in os.listdir(test_path):
    print(folder)


bart_simpson
charles_montgomery_burns
homer_simpson
krusty_the_clown
lisa_simpson
marge_simpson
milhouse_van_houten
moe_szyslak
ned_flanders
principal_skinner


In [8]:
for folder in os.listdir(train_path):
    print(folder)

bart_simpson
charles_montgomery_burns
homer_simpson
krusty_the_clown
lisa_simpson
marge_simpson
milhouse_van_houten
moe_szyslak
ned_flanders
principal_skinner


## Create a dictionary to map indices to folder names in the training path:

In [10]:
folder_dict = {idx: folder for idx, folder in enumerate(os.listdir(train_path))}
print(folder_dict)

{0: 'bart_simpson', 1: 'charles_montgomery_burns', 2: 'homer_simpson', 3: 'krusty_the_clown', 4: 'lisa_simpson', 5: 'marge_simpson', 6: 'milhouse_van_houten', 7: 'moe_szyslak', 8: 'ned_flanders', 9: 'principal_skinner'}


## Inititalizing empty lists to store train and test images and labels:

In [11]:
training_image_set = []
training_image_label = []

for i, folder_name in enumerate(os.listdir(train_path)):
    current_folder = os.path.join(train_paSth, folder_name)
    
    for image_name in os.listdir(current_folder):
        img = cv.imread(os.path.join(current_folder, image_name))   ##Read each image in the folder using OpenCV
        training_image_set.append(img.flatten() / 255)  ##Flattening the image array and normalizing it ##Appending the flattened image to training_image_set.
        training_image_label.append(i)   ##Appending the corresponding index to training_image_label.

test_image_set = []  ## Same loop iterating through testing dataset
test_image_label = []

for i, folder_name in enumerate(os.listdir(test_path)):
    current_folder = os.path.join(test_path, folder_name)
    
    for image_name in os.listdir(current_folder):
        img = cv.imread(os.path.join(current_folder, image_name))
        test_image_set.append(img.flatten() / 255)
        test_image_label.append(i)

In [12]:
training_image_set = np.array(training_image_set).T   ##Converting the list of image arrays into a NumPy array. Each column of the array corresponds to flattened image.
training_image_label = np.array(training_image_label)

In [13]:
test_image_set = np.array(test_image_set).T  ##Same thing through test dataset.Swapping the rows and columns of the array.
test_image_label = np.array(test_image_label)

## Printing the shape of testing image 

In [14]:
print(test_image_set.shape)

(2352, 2000)


## Initialization of Parameters
## Implementing Sigmoid Activation Function
## Implementing Softmax Activation Function
## Implementing Forward Propagation
## Sigmoid Prime (Derivating of Sigmoid function)
## One-Hot Encoding
## Backward Propagation implementation 
## Parameter Update









In [26]:
n, m = training_image_set.shape
def init_params():
    W1 = np.random.rand(10, 2352) - 0.5
    b1 = np.random.rand(10, 1) - 0.5
    W2 = np.random.rand(10, 10) - 0.5
    b2 = np.random.rand(10, 1) - 0.5
    return W1, b1, W2, b2

def sigmoid(z):
    return 1.0/(1.0+np.exp(-z))

def softmax(Z):
    A = np.exp(Z) / sum(np.exp(Z))
    return A
    
def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = sigmoid(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

def sigmoid_prime(z):
    return sigmoid(z)*(1-sigmoid(z))

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y):
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2)
    dZ1 = W2.T.dot(dZ2) * sigmoid_prime(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1)
    return dW1, db1, dW2, db2

def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1    
    W2 = W2 - alpha * dW2  
    b2 = b2 - alpha * db2    
    return W1, b1, W2, b2

## Getting the predicted labels
## Comparing the predicted and actual labels
## Performing gradient descent to train neural network model
## And returning the updated parameters

In [27]:
def get_predictions(A2):            ##It defines a function that takes the output activations 'A2' and returns the indexes of the maximum value along axis 0
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):   ##Function that comparespredicted labels with actual labels and printing them and return accuracy.
    print(predictions, Y) 
    return np.sum(predictions == Y) / Y.size

def gradient_descent(X, Y, alpha, iterations):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if i % 100 == 0:
            print("Iteration: ", i)
            predictions = get_predictions(A2)
            print(get_accuracy(predictions, Y))
            
    return W1, b1, W2, b2

## Assigning the returned values from gradient descent func. to these 4 variables:

In [29]:
W1, b1, W2, b2 = gradient_descent(training_image_set, training_image_label, 0.1,50000)

Iteration:  0
[3 3 3 ... 3 3 5] [0 0 0 ... 9 9 9]
0.089
Iteration:  100
[7 9 6 ... 2 2 5] [0 0 0 ... 9 9 9]
0.117
Iteration:  200
[7 7 2 ... 2 2 5] [0 0 0 ... 9 9 9]
0.11775
Iteration:  300
[7 7 2 ... 2 2 6] [0 0 0 ... 9 9 9]
0.120375
Iteration:  400
[7 0 2 ... 2 5 0] [0 0 0 ... 9 9 9]
0.126125
Iteration:  500
[7 0 2 ... 5 0 7] [0 0 0 ... 9 9 9]
0.138125
Iteration:  600
[1 0 2 ... 5 0 9] [0 0 0 ... 9 9 9]
0.14825
Iteration:  700
[1 0 5 ... 5 0 9] [0 0 0 ... 9 9 9]
0.15875
Iteration:  800
[1 3 5 ... 5 0 1] [0 0 0 ... 9 9 9]
0.164375
Iteration:  900
[1 2 5 ... 5 1 1] [0 0 0 ... 9 9 9]
0.167625
Iteration:  1000
[1 2 5 ... 5 1 0] [0 0 0 ... 9 9 9]
0.1705
Iteration:  1100
[1 2 5 ... 5 1 0] [0 0 0 ... 9 9 9]
0.1755
Iteration:  1200
[1 2 5 ... 5 1 0] [0 0 0 ... 9 9 9]
0.177375
Iteration:  1300
[1 2 5 ... 5 1 0] [0 0 0 ... 9 9 9]
0.180875
Iteration:  1400
[1 2 5 ... 5 1 0] [0 0 0 ... 9 9 9]
0.18475
Iteration:  1500
[1 2 5 ... 5 1 0] [0 0 0 ... 9 9 9]
0.187375
Iteration:  1600
[1 2 5 ... 5 1 0]

In [30]:
def make_predictions(X, W1, b1, W2, b2):
    _, _, _, A2 = forward_propagation(W1, b1, W2, b2, X)
    predictions = get_predictions(A2)
    return predictions

def test_prediction(index, W1, b1, W2, b2):
    current_image = test_image_set[:, index, None]
    prediction = make_predictions(current_image, W1, b1, W2, b2)
    label = test_image_label[index]
    return prediction[0], label

In [32]:
predictions = np.array([test_prediction(i, W1, b1, W2, b2)[0] for i in range(len(test_image_label))])
correct_predictions = np.sum(predictions == test_image_label)
accuracy = correct_predictions / len(test_image_label) * 100

print(f"Test Accuracy: {accuracy:.2f}%")



Test Accuracy: 27.45%
